organize applications into matrix config

diff --git a/.github/workflows/build_all_application_deps.yaml b/.github/workflows/build_all_application_deps.yaml
--- a/.github/workflows/build_all_application_deps.yaml
+++ b/.github/workflows/build_all_application_deps.yaml
@@ -12,31 +12,16 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
+        application: [ufs-weather-model, gsi, nceplibs-develop, nceplibs-numbered]
         config:
-        - {
-            compiler: "gcc",
-            compiler-version: "13",
-            os: "ubuntu-24.04",
-            mpi: "mpich",
-            mpi-version: ":",
-            applications: ["ufs-weather-model", "gsi", "nceplibs-develop", "nceplibs-numbered"],
-          }
-        - {
-            compiler: "classic",
-            compiler-version: "2023.2.1",
-            os: "ubuntu-24.04",
-            mpi: "intel-oneapi-mpi",
-            mpi-version: "2021.14",
-            applications: ["nceplibs-develop", "nceplibs-numbered"],
-          }
-        - {
-            compiler: "oneapi",
-            compiler-version: "2025.3",
-            os: "ubuntu-24.04",
-            mpi: "intel-oneapi-mpi",
-            mpi-version: "2021.14",
-            applications: ["ufs-weather-model", "nceplibs-develop", "nceplibs-numbered"],
-          }
+        - {compiler: gcc, compiler-version: "13", os: ubuntu-24.04, mpi: mpich, mpi-version: ":"}
+        - {compiler: classic, compiler-version: "2023.2.1", os: ubuntu-24.04, mpi: intel-oneapi-mpi, mpi-version: "2021.14"}
+        - {compiler: oneapi, compiler-version: "2025.3", os: ubuntu-24.04, mpi: intel-oneapi-mpi, mpi-version: "2021.14"}
+        exclude:
+        - application: gsi
+          config: {compiler: classic}
+        - application: gsi
+          config: {compiler: oneapi}
     runs-on: ${{ matrix.config.os }}
     permissions:
       packages: write
@@ -75,8 +60,9 @@ jobs:
           
           # Wrap spack command to echo before executing
           spack() {
-            echo "Running: spack $@"
+            echo "::group:: spack $@"
             _spack_shell_wrapper "$@";
+            echo "::endgroup::"
             return $?
           }
           
@@ -90,104 +76,95 @@ jobs:
           spack mirror add emc-common-build-cache oci://ghcr.io/$OCI_USERNAME/ci-common-build-cache
           spack mirror set --push --oci-username-variable OCI_USERNAME --oci-password-variable OCI_TOKEN emc-common-build-cache
 
-          # Loop through each application
-          for app in ${{ join(matrix.config.applications, ' ') }}; do
-            echo "::group:: Building application dependencies: ${app}"
-            echo "Processing application: ${app}"
+          app=${{ matrix.application }}
+          echo "Processing application: ${app}"
 
-            # Create and activate environment from manifest
-            spack env create ${app}-env applications/${app}.yaml
-            spack env activate ${app}-env
-            spack config add 'config:install_tree:padded_length:200'
-            spack repo add ${GITHUB_WORKSPACE}/custom_repo
+          # Create and activate environment from manifest
+          spack env create ${app}-env applications/${app}.yaml
+          spack env activate ${app}-env
+          spack config add 'config:install_tree:padded_length:200'
+          spack repo add ${GITHUB_WORKSPACE}/custom_repo
 
-            # Set up compilers & MPI for this application
-            COMPILER=${{ matrix.config.compiler }}@${{ matrix.config.compiler-version }}
-            if [ ${{ matrix.config.compiler }} == 'gcc' ]; then
-              sudo apt install gcc-${{ matrix.config.compiler-version }} g++-${{ matrix.config.compiler-version }} gfortran-${{ matrix.config.compiler-version }}
-              spack config add "packages:gcc-runtime:require:'%gcc@${{ matrix.config.compiler-version }}'"
-            else # set GCC backend for Intel to be the Ubuntu default version of GCC
-              if [ ${{ matrix.config.os }} == ubuntu-22.04 ]; then gccver=11; fi
-              if [ ${{ matrix.config.os }} == ubuntu-24.04 ]; then gccver=13; fi
-              spack config add "packages:gcc-runtime:require:'%gcc@${gccver}'"
-            fi
-            if [ ${{ matrix.config.compiler }} == 'oneapi' ]; then
-              spack compiler find /opt/intel/oneapi/compiler/${{ matrix.config.compiler-version }}
-              spack compiler find /opt/intel/oneapi/compiler/${{ matrix.config.compiler-version }}/linux
-              COMPILER=intel-oneapi-compilers
-            elif [ ${{ matrix.config.compiler }} == 'classic' ]; then
-              which icc
-              spack external find intel-oneapi-compilers-classic
-              COMPILER=intel-oneapi-compilers-classic
-              CLASSIC_LD_PATH='/opt/intel/oneapi/compiler/${{ matrix.config.compiler-version }}/linux/compiler/lib/intel64_lin'
-            fi
-            compilerstoallow="'%${COMPILER}'"
-            if [[ " oneapi classic " =~ " ${{ matrix.config.compiler }} " ]]; then
-              compilerstoallow="${compilerstoallow},'%gcc@${gccver}'"
-              # Fix libimf.so not found issue AND 2025.3.x mismatch issue
-              spack fix-intel-config --consolidate
-            fi
-            allowedcompilerspecs=$(echo $compilerstoallow | sed "s:%::g;s:,: :;s:'::g")
+          # Set up compilers & MPI for this application
+          COMPILER=${{ matrix.config.compiler }}@${{ matrix.config.compiler-version }}
+          if [ ${{ matrix.config.compiler }} == 'gcc' ]; then
+            sudo apt install gcc-${{ matrix.config.compiler-version }} g++-${{ matrix.config.compiler-version }} gfortran-${{ matrix.config.compiler-version }}
+            spack config add "packages:gcc-runtime:require:'%gcc@${{ matrix.config.compiler-version }}'"
+          else # set GCC backend for Intel to be the Ubuntu default version of GCC
+            if [ ${{ matrix.config.os }} == ubuntu-22.04 ]; then gccver=11; fi
+            if [ ${{ matrix.config.os }} == ubuntu-24.04 ]; then gccver=13; fi
+            spack config add "packages:gcc-runtime:require:'%gcc@${gccver}'"
+          fi
+          if [ ${{ matrix.config.compiler }} == 'oneapi' ]; then
+            spack compiler find /opt/intel/oneapi/compiler/${{ matrix.config.compiler-version }}
+            spack compiler find /opt/intel/oneapi/compiler/${{ matrix.config.compiler-version }}/linux
+            COMPILER=intel-oneapi-compilers
+          elif [ ${{ matrix.config.compiler }} == 'classic' ]; then
+            which icc
+            spack external find intel-oneapi-compilers-classic
+            COMPILER=intel-oneapi-compilers-classic
+            CLASSIC_LD_PATH='/opt/intel/oneapi/compiler/${{ matrix.config.compiler-version }}/linux/compiler/lib/intel64_lin'
+          fi
+          compilerstoallow="'%${COMPILER}'"
+          if [[ " oneapi classic " =~ " ${{ matrix.config.compiler }} " ]]; then
+            compilerstoallow="${compilerstoallow},'%gcc@${gccver}'"
+            # Fix libimf.so not found issue AND 2025.3.x mismatch issue
+            spack fix-intel-config --consolidate
+          fi
+          allowedcompilerspecs=$(echo $compilerstoallow | sed "s:%::g;s:,: :;s:'::g")
 
-            spack config add "concretizer:reuse:include:[${compilerstoallow}]"
-            spack config add "packages:all:prefer:['%$COMPILER']"
-            spack config add "packages:all:require:'target=x86_64'"
-            # The following is a problem for CRTM:
-            spack config add "packages:fortran:require:['$COMPILER']"
+          spack config add "concretizer:reuse:include:[${compilerstoallow}]"
+          spack config add "packages:all:prefer:['%$COMPILER']"
+          spack config add "packages:all:require:'target=x86_64'"
+          # The following is a problem for CRTM:
+          spack config add "packages:fortran:require:['$COMPILER']"
 
-            spack config add "packages:mpi:require:'${{ matrix.config.mpi }}@${{ matrix.config.mpi-version }}'"
-            if [ "${{ matrix.config.mpi }}" == intel-oneapi-mpi ]; then
-              sed -i "s|^  packages:|  packages:\n    intel-oneapi-mpi:\n      buildable: false\n      externals:\n      - spec: intel-oneapi-mpi@${{ matrix.config.mpi-version }}\n        prefix: /opt/intel/oneapi|" $SPACK_ENV/spack.yaml
-              spack config add "packages:mpi:buildable:false"
-            fi
+          spack config add "packages:mpi:require:'${{ matrix.config.mpi }}@${{ matrix.config.mpi-version }}'"
+          if [ "${{ matrix.config.mpi }}" == intel-oneapi-mpi ]; then
+            sed -i "s|^  packages:|  packages:\n    intel-oneapi-mpi:\n      buildable: false\n      externals:\n      - spec: intel-oneapi-mpi@${{ matrix.config.mpi-version }}\n        prefix: /opt/intel/oneapi|" $SPACK_ENV/spack.yaml
+            spack config add "packages:mpi:buildable:false"
+          fi
 
-            spack external find gcc git git-lfs
-            # Avoid various C++-related Intel compiler bugs by building some packages with GCC:
-            for pkg in diffutils sed grep libidn2 tar berkeley-db gettext findutils cmake libiconv; do
-              spack config add "packages:${pkg}:require:'%gcc'"
-            done
-            spack filter-compilers $allowedcompilerspecs --keep-only
-            cat $SPACK_ENV/spack.yaml
-
-            # Concretize environment
-            spack concretize --fresh |& tee log.concretize.${app}
-
-            # Validate
-            spack validate compilers $allowedcompilerspecs
-            if [[ " oneapi classic " =~ " ${{ matrix.config.compiler }} " ]]; then
-              spack validate allow-pkgs-for-compiler gcc cmake diffutils
-            fi
-
-            # If running from the cron trigger, rebuild from scratch
-            if [ ! -z '${{ github.event.schedule }}' ]; then NOCACHE="--no-cache"; fi
-            spack config add 'config:build_stage:~/spack'
-
-            # Don't immediately exit job on failed 'spack install' so we can still cache whatever was built:
-            set +e
-            spack install --no-check-signature --show-log-on-error --fail-fast $NOCACHE
-            app_rc=$?
-            set -e
-
-            # Push to buildcache under GitHub Packages (OCI repo)
-            spack buildcache push --update-index --unsigned --with-build-dependencies emc-common-build-cache
-
-            # Generate container image for this application
-            label=${{ matrix.config.os }}-${{ matrix.config.compiler }}-${{ matrix.config.compiler-version }}-${{ matrix.config.mpi }}-${{ matrix.config.mpi-version }}
-            label=${label//:/x}
-            spack mirror add \
-              --oci-username-variable OCI_USERNAME \
-              --oci-password-variable OCI_TOKEN \
-              ${app}-env oci://ghcr.io/${OCI_USERNAME,,}/ci-common-build-cache/${app}-${label}
-            image=$(echo ${{ matrix.config.os }} | sed 's|-|:|')
-            echo "Creating consolidated container image ${image}"
-            spack buildcache push --only dependencies --with-build-dependencies --update-index --unsigned \
-              --base-image ${image} --tag latest ${app}-env |& perl -pe 's/.+(Fetching|Using cached)/::debug::\1/'
-
-            if [ $app_rc -ne 0 ]; then echo "install-time error!"; exit 1; fi
-
-            # Deactivate environment and clean up for next iteration
-            spack env deactivate
-            spack env rm -y ${app}-env
-            
-            echo "::endgroup::"
+          spack external find gcc git git-lfs
+          # Avoid various C++-related Intel compiler bugs by building some packages with GCC:
+          for pkg in diffutils sed grep libidn2 tar berkeley-db gettext findutils cmake libiconv; do
+            spack config add "packages:${pkg}:require:'%gcc'"
           done
+          spack filter-compilers $allowedcompilerspecs --keep-only
+          cat $SPACK_ENV/spack.yaml
+
+          # Concretize environment
+          spack concretize --fresh |& tee log.concretize.${app}
+
+          # Validate
+          spack validate compilers $allowedcompilerspecs
+          if [[ " oneapi classic " =~ " ${{ matrix.config.compiler }} " ]]; then
+            spack validate allow-pkgs-for-compiler gcc cmake diffutils
+          fi
+
+          # If running from the cron trigger, rebuild from scratch
+          if [ ! -z '${{ github.event.schedule }}' ]; then NOCACHE="--no-cache"; fi
+          spack config add 'config:build_stage:~/spack'
+
+          # Don't immediately exit job on failed 'spack install' so we can still cache whatever was built:
+          set +e
+          spack install --no-check-signature --show-log-on-error --fail-fast $NOCACHE
+          app_rc=$?
+          set -e
+
+          # Push individual packages to GitHub Packages build cache (OCI repo)
+          spack buildcache push --update-index --unsigned --with-build-dependencies emc-common-build-cache |& perl -pe 's/.+(Fetching|Using cached)/::debug::\1/'
+
+          # Generate container image for this application
+          label=${{ matrix.config.os }}-${{ matrix.config.compiler }}-${{ matrix.config.compiler-version }}-${{ matrix.config.mpi }}-${{ matrix.config.mpi-version }}
+          label=${label//:/x}
+          spack mirror add \
+            --oci-username-variable OCI_USERNAME \
+            --oci-password-variable OCI_TOKEN \
+            ${app}-env oci://ghcr.io/${OCI_USERNAME,,}/ci-common-build-cache/${app}-${label}
+          image=$(echo ${{ matrix.config.os }} | sed 's|-|:|')
+          echo "Creating consolidated container image for ${app}"
+          spack buildcache push --only dependencies --with-build-dependencies --update-index --unsigned \
+            --base-image ${image} --tag latest ${app}-env |& perl -pe 's/.+(Fetching|Using cached)/::debug::\1/'
+
+          if [ $app_rc -ne 0 ]; then echo "install-time error!"; exit 1; fi
