consistently put spack-packages in SPACK_ROOT

diff --git a/.github/workflows/build_all_application_deps.yaml b/.github/workflows/build_all_application_deps.yaml
--- a/.github/workflows/build_all_application_deps.yaml
+++ b/.github/workflows/build_all_application_deps.yaml
@@ -96,12 +96,12 @@ jobs:
           
           spack config add 'config:install_tree:padded_length:200'
 
-          # Materialize spack-packages directly under $SPACK_ENV.
-          spack_packages_repo_url=https://github.com/JCSDA/spack-packages
-          spack repo add "$spack_packages_repo_url" '$env/spack-packages'
-          spack_packages_commit=$(git -C "$SPACK_ENV/spack-packages" rev-parse HEAD || true)
+          # Materialize spack-packages directly under $SPACK_ROOT.
+          spack_packages_repo_url=https://github.com/spack/spack-packages
+          spack repo add "$spack_packages_repo_url" --destination '$spack/spack-packages'
+          spack_packages_commit=$(git -C "$SPACK_ROOT/spack-packages" rev-parse HEAD || true)
           if [[ -z "${spack_packages_commit}" ]]; then
-            echo "Unable to resolve commit for ${SPACK_ENV}/spack-packages"
+            echo "Unable to resolve commit for ${SPACK_ROOT}/spack-packages"
             exit 1
           fi
           echo "spack-packages origin: ${spack_packages_repo_url}"
